version: '3.8'

services:
  auriga-api:
    image: auriga-api:0.0.01
    container_name: auriga-api
    ports:
      - "${AURIGA_API_PORT}:8081"
    environment:
      - AURIGA_API_PORT=${AURIGA_API_PORT}
      - AURIGA_NAME=${AURIGA_NAME}
      - AURIGA_VERSION=${AURIGA_VERSION}
      - AURIGA_ZAP=${AURIGA_ZAP}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_TIMEZONE=${DATABASE_TIMEZONE}
      - GRAFANA1_HOST=${GRAFANA1_HOST}
      - GRAFANA1_PORT=${GRAFANA1_PORT}
      - GRAFANA2_HOST=${GRAFANA2_HOST}
      - GRAFANA2_PORT=${GRAFANA2_PORT}
      

      - CXB_INFLUXDB_HOST=${CXB_INFLUXDB_HOST}
      - CXB_INFLUXDB_PORT=${CXB_INFLUXDB_PORT}
      - CXB_INFLUXDB_TOKEN=${CXB_INFLUXDB_TOKEN}
      - CXB_INFLUXDB_ORG=${CXB_INFLUXDB_ORG}
      - CXB_INFLUXDB_BUCKET=${CXB_INFLUXDB_BUCKET}
      
      - CXC_INFLUXDB_HOST=${CXC_INFLUXDB_HOST}
      - CXC_INFLUXDB_PORT=${CXC_INFLUXDB_PORT}
      - CXC_INFLUXDB_TOKEN=${CXC_INFLUXDB_TOKEN}
      - CXC_INFLUXDB_ORG=${CXC_INFLUXDB_ORG}
      - CXC_INFLUXDB_BUCKET=${CXC_INFLUXDB_BUCKET}
      
      - CXD_INFLUXDB_HOST=${CXD_INFLUXDB_HOST}
      - CXD_INFLUXDB_PORT=${CXD_INFLUXDB_PORT}
      - CXD_INFLUXDB_TOKEN=${CXD_INFLUXDB_TOKEN}
      - CXD_INFLUXDB_ORG=${CXD_INFLUXDB_ORG}
      - CXD_INFLUXDB_BUCKET=${CXD_INFLUXDB_BUCKET}
      
      - CXE_INFLUXDB_HOST=${CXE_INFLUXDB_HOST}
      - CXE_INFLUXDB_PORT=${CXE_INFLUXDB_PORT}
      - CXE_INFLUXDB_TOKEN=${CXE_INFLUXDB_TOKEN}
      - CXE_INFLUXDB_ORG=${CXE_INFLUXDB_ORG}
      - CXE_INFLUXDB_BUCKET=${CXE_INFLUXDB_BUCKET}
      
      - CXF_INFLUXDB_HOST=${CXF_INFLUXDB_HOST}
      - CXF_INFLUXDB_PORT=${CXF_INFLUXDB_PORT}
      - CXF_INFLUXDB_TOKEN=${CXF_INFLUXDB_TOKEN}
      - CXF_INFLUXDB_ORG=${CXF_INFLUXDB_ORG}
      - CXF_INFLUXDB_BUCKET=${CXF_INFLUXDB_BUCKET}
      
      - CXM_INFLUXDB_HOST=${CXM_INFLUXDB_HOST}
      - CXM_INFLUXDB_PORT=${CXM_INFLUXDB_PORT}
      - CXM_INFLUXDB_TOKEN=${CXM_INFLUXDB_TOKEN}
      - CXM_INFLUXDB_ORG=${CXM_INFLUXDB_ORG}
      - CXM_INFLUXDB_BUCKET=${CXM_INFLUXDB_BUCKET}
      
      - EXT_INFLUXDB_HOST=${EXT_INFLUXDB_HOST}
      - EXT_INFLUXDB_PORT=${EXT_INFLUXDB_PORT}
      - EXT_INFLUXDB_TOKEN=${EXT_INFLUXDB_TOKEN}
      - EXT_INFLUXDB_ORG=${EXT_INFLUXDB_ORG}
      - EXT_INFLUXDB_BUCKET=${EXT_INFLUXDB_BUCKET}
      
      - FPC_INFLUXDB_HOST=${FPC_INFLUXDB_HOST}
      - FPC_INFLUXDB_PORT=${FPC_INFLUXDB_PORT}
      - FPC_INFLUXDB_TOKEN=${FPC_INFLUXDB_TOKEN}
      - FPC_INFLUXDB_ORG=${FPC_INFLUXDB_ORG}
      - FPC_INFLUXDB_BUCKET=${FPC_INFLUXDB_BUCKET}
      
      - FPB_INFLUXDB_HOST=${FPB_INFLUXDB_HOST}
      - FPB_INFLUXDB_PORT=${FPB_INFLUXDB_PORT}
      - FPB_INFLUXDB_TOKEN=${FPB_INFLUXDB_TOKEN}
      - FPB_INFLUXDB_ORG=${FPB_INFLUXDB_ORG}
      - FPB_INFLUXDB_BUCKET=${FPB_INFLUXDB_BUCKET}
      
      - FSP_INFLUXDB_HOST=${FSP_INFLUXDB_HOST}
      - FSP_INFLUXDB_PORT=${FSP_INFLUXDB_PORT}
      - FSP_INFLUXDB_TOKEN=${FSP_INFLUXDB_TOKEN}
      - FSP_INFLUXDB_ORG=${FSP_INFLUXDB_ORG}
      - FSP_INFLUXDB_BUCKET=${FSP_INFLUXDB_BUCKET}
      
      - MNT_INFLUXDB_HOST=${MNT_INFLUXDB_HOST}
      - MNT_INFLUXDB_PORT=${MNT_INFLUXDB_PORT}
      - MNT_INFLUXDB_TOKEN=${MNT_INFLUXDB_TOKEN}
      - MNT_INFLUXDB_ORG=${MNT_INFLUXDB_ORG}
      - MNT_INFLUXDB_BUCKET=${MNT_INFLUXDB_BUCKET}

      - SAPDB_URL=${SAPDB_URL}
      - SAPDB_AUTH=${SAPDB_AUTH}

      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - AUTHENTIK_REDIRECT_URL=${AUTHENTIK_REDIRECT_URL}
      - AUTHENTIK_JWKS_ENDPOINT=${AUTHENTIK_JWKS_ENDPOINT}

      - WORKERA_URL=${WORKERA_URL}
      - WORKERA_API_USER=${WORKERA_API_USER}
      - WORKERA_API_KEY=${WORKERA_API_KEY}
    restart: unless-stopped



# sudo docker compose -f docker-compose.yml up -d
